from sqlalchemy import Column, String, Integer, Float, Boolean, JSON
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class Product(Base):
    __tablename__ = "products"
    id = Column(String, primary_key=True, index=True)
    name = Column(String)
    handle = Column(String)
    description = Column(String)
    category = Column(String)
    categories = Column(JSON)
    tags = Column(JSON)
    featuredImageId = Column(String)
    images = Column(JSON)
    priceTaxExcl = Column(Float)
    priceTaxIncl = Column(Float)
    taxRate = Column(Float)
    comparedPrice = Column(Float)
    quantity = Column(Float)
    sku = Column(String)
    width = Column(String)
    height = Column(String)
    depth = Column(String)
    weight = Column(String)
    extraShippingFee = Column(Float)
    active = Column(Boolean)
    title = Column(String)
    slug = Column(String)
    duration = Column(Integer)
    totalSteps = Column(Integer)
    updatedAt = Column(String)
    featured = Column(Boolean)
    progress = Column(JSON)
    steps = Column(JSON)
    summaries = Column(JSON)

class Sumdoc(Base):
    __tablename__ = "sumdocs"
    id = Column(String, primary_key=True, index=True)
    name = Column(String)
    handle = Column(String)
    description = Column(String)
    category = Column(String)
    categories = Column(JSON)
    tags = Column(JSON)
    featuredImageId = Column(String)
    images = Column(JSON)
    priceTaxExcl = Column(Float)
    priceTaxIncl = Column(Float)
    taxRate = Column(Float)
    comparedPrice = Column(Float)
    quantity = Column(Float)
    sku = Column(String)
    width = Column(String)
    height = Column(String)
    depth = Column(String)
    weight = Column(String)
    extraShippingFee = Column(Float)
    active = Column(Boolean)
    title = Column(String)
    slug = Column(String)
    duration = Column(Integer)
    totalSteps = Column(Integer)
    updatedAt = Column(String)
    featured = Column(Boolean)
    progress = Column(JSON)
    steps = Column(JSON)
    summaries = Column(JSON)

class SummaryTask(Base):
    __tablename__ = "summary_tasks"
    id = Column(String, primary_key=True, index=True)
    sumdocId = Column(String)
    status = Column(String)
    errorMessage = Column(String)
    model = Column(String)
    summary = Column(String)
    retryCount = Column(Integer)
    createdAt = Column(String)
    updatedAt = Column(String)